language: ruby
rvm:
- 2.4.1
script: "./bin/cibuild"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: 
    recipients:
      - bhsbhs235@naver.com
    on_success: never 
    on_failure: always 