title:              효성's Blog
email:              bhsbhs235@naver.com
description:       Software Engineer
author:             Start Bootstrap
#baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://bhsbhs235.github.io"
category_dir: category/


#Social Profiles
#twitter_username:   SBootstrap
github_username:    bhsbhs235
#facebook_username:  StartBootstrap
linkedin_username: hyo-seong-bae-15a044199

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-151419070-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
